import { useEffect, useRef, useState } from 'react'
import JSZip from 'jszip'
import { saveAs } from 'file-saver'
import { open } from '@tauri-apps/plugin-dialog'
import { isTauri, writeFileToDir, sanitizePathSegment } from '../../lib/tauri'
import { useProjectStore } from '../../store/useProjectStore'
import { renderSlide, renderSpanGroup } from '../../lib/renderSlide'
import { ascExportCode, SUPPORTED_LOCALES } from '../../constants/defaults'
import { typeOfModel } from '../../constants/deviceSpecs'
import { getUntranslatedLocales, getSlidesMissingScreenshot } from '../../lib/readiness'
import type { DeviceType, Slide } from '../../types/project'

function deviceOf(slide: Slide): DeviceType {
  return typeOfModel(slide.deviceFrame.model)
}

const localeLabel = (code: string) =>
  SUPPORTED_LOCALES.find((l) => l.code === code)?.label ?? code
// Canonical display order for locales (SUPPORTED_LOCALES order: en, ko, ja, …).
const localeOrder = (code: string) => {
  const i = SUPPORTED_LOCALES.findIndex((l) => l.code === code)
  return i < 0 ? 999 : i
}

type Status = 'idle' | 'running' | 'done' | 'error'

// One slide+locale that failed to render/emit during an export run. The batch
// continues past it; these are collected and shown as a persistent list.
type RenderFailure = { slideNo: number; locale: string; device: DeviceType; message: string }

// 'default' = human-organized {locale}/{device}/NN.png.
// 'fastlane' = `deliver` layout: screenshots/{ascLocale}/{device}_NN.png, flat
// under each locale (deliver doesn't recurse and infers the device from image
// resolution), so `fastlane deliver` can upload the folder as-is.
type ExportLayout = 'default' | 'fastlane'

const FASTLANE_README = `App Store screenshot upload via fastlane deliver
==================================================

This archive is a ready-to-run fastlane setup. Three steps:

1. Edit fastlane/Appfile — set app_identifier to your app's bundle id.

2. Create an App Store Connect API key and fill asc_api_key.json:
   App Store Connect -> Users and Access -> Integrations -> App Store Connect API
   -> generate a key, download the .p8, note the Key ID and Issuer ID, then paste
   them (and the .p8 contents) into asc_api_key.json.

3. From this folder, run:
   ./upload.sh
   (or: fastlane deliver --api_key_path ./asc_api_key.json)

Notes
- screenshots/ folders are App Store Connect locale codes; the device is
  auto-detected from each image's resolution.
- Only screenshots are uploaded (binary + store metadata are skipped).
- Your .p8 key stays on this machine — nothing is sent anywhere but Apple.
- Requires fastlane: https://docs.fastlane.tools/getting-started/ios/setup/
`

const FASTLANE_APPFILE = `# Set your app's bundle identifier (e.g. com.yourcompany.app).
app_identifier("YOUR.BUNDLE.ID")
`

const FASTLANE_DELIVERFILE = `# Generated by App Store Screenshot Studio.
# Upload screenshots only — never touch the binary or store metadata.
overwrite_screenshots(true)
skip_binary_upload(true)
skip_metadata(true)
# screenshots_path defaults to ./fastlane/screenshots
`

const FASTLANE_KEY_EXAMPLE = `{
  "key_id": "YOUR_KEY_ID",
  "issuer_id": "YOUR_ISSUER_ID",
  "key": "-----BEGIN PRIVATE KEY-----\\nPASTE_YOUR_P8_CONTENTS_HERE\\n-----END PRIVATE KEY-----",
  "duration": 1200,
  "in_house": false
}
`

const FASTLANE_UPLOAD_SH = `#!/usr/bin/env bash
set -euo pipefail
# 1) Edit fastlane/Appfile (app_identifier) and asc_api_key.json (API key).
# 2) Run: ./upload.sh
fastlane deliver \\
  --api_key_path ./asc_api_key.json \\
  --overwrite_screenshots true \\
  --skip_binary_upload true \\
  --skip_metadata true
`

export function ExportPanel() {
  const project = useProjectStore((s) => s.project)
  const setStep = useProjectStore((s) => s.setStep)

  const [status, setStatus] = useState<Status>('idle')
  const [done, setDone] = useState(0)
  const [error, setError] = useState<string | null>(null)
  // Per-slide render failures collected during a run so one bad slide can't
  // abort the whole batch; surfaced as a persistent list after export.
  const [failures, setFailures] = useState<RenderFailure[]>([])
  // What's currently rendering, for progress granularity ("슬라이드 5 · German").
  const [current, setCurrent] = useState<{ slideNo: number; locale: string } | null>(null)
  const cancelledRef = useRef(false)

  const [previewLocale, setPreviewLocale] = useState<string>('')
  const [previewSrcs, setPreviewSrcs] = useState<(string | null)[]>([])
  const [previewLoading, setPreviewLoading] = useState(false)
  const prevUrlsRef = useRef<(string | null)[]>([])
  // Preview thumbnail size: 1 (small, more columns) … 5 (large, single column).
  const [previewSize, setPreviewSize] = useState(1)
  // Locales the user unticked for export; empty = export everything.
  const [excludedLocales, setExcludedLocales] = useState<Set<string>>(new Set())

  // Auto-render every slide for the chosen locale — no button. Re-runs whenever
  // the project or preview locale changes; a cancelled flag drops stale results
  // if the locale flips mid-render.
  const previewLocaleEff = previewLocale || project?.sourceLocale
  useEffect(() => {
    if (!project) return
    let cancelled = false
    const slides = project.slides
    const renderLocale = previewLocaleEff === project.sourceLocale ? null : previewLocaleEff!
    ;(async () => {
      setPreviewLoading(true)
      const urls: (string | null)[] = []
      for (const slide of slides) {
        if (cancelled) break
        try {
          let blob: Blob
          if (slide.spanGroupId) {
            const isLeader = slide.spanRole === 'leader'
            const leader = isLeader
              ? slide
              : slides.find((s) => s.spanGroupId === slide.spanGroupId && s.spanRole === 'leader')
            if (!leader) {
              urls.push(null)
              continue
            }
            // Render at full export resolution (no preview width) so the
            // thumbnail is byte-identical to the exported PNG — absolute-pixel
            // constants (fit-to-box floor, headline gap) otherwise diverge
            // between the 440px preview scale and the export scale. CSS scales it
            // down for display.
            const halves = await renderSpanGroup(leader, renderLocale)
            blob = isLeader ? halves.leader : halves.follower
          } else {
            blob = await renderSlide(slide, renderLocale)
          }
          urls.push(URL.createObjectURL(blob))
        } catch {
          urls.push(null)
        }
      }
      if (cancelled) {
        urls.forEach((u) => u && URL.revokeObjectURL(u))
        return
      }
      prevUrlsRef.current.forEach((u) => u && URL.revokeObjectURL(u))
      prevUrlsRef.current = urls
      setPreviewSrcs(urls)
      setPreviewLoading(false)
    })()
    return () => {
      cancelled = true
    }
  }, [project, previewLocaleEff])

  // Revoke the last committed preview blobs when the panel unmounts (the effect
  // above only revokes the *previous* set on each re-run, never the final one).
  useEffect(() => () => prevUrlsRef.current.forEach((u) => u && URL.revokeObjectURL(u)), [])

  if (!project) return null

  // Source first, then targets in canonical order (Korean right after the
  // source, then Japanese, …) — deduped so a locale left in targetLocales from
  // before a source switch can't export the same folder twice.
  const allLocales = [
    project.sourceLocale,
    ...[...new Set(project.targetLocales)]
      .filter((l) => l !== project.sourceLocale)
      .sort((a, b) => localeOrder(a) - localeOrder(b)),
  ]
  const exportLocales = allLocales.filter((l) => !excludedLocales.has(l))
  const previewCols = 6 - previewSize
  // Each slide exports to exactly one device — the one its screenshot belongs
  // to (auto-detected on upload). project.devices is no longer multiplied in.
  const total = project.slides.length * exportLocales.length
  const untranslated = getUntranslatedLocales(project)
  const missingScreenshots = getSlidesMissingScreenshot(project)
  const devicesInUse = Array.from(new Set(project.slides.map(deviceOf)))

  const effectiveLocale = previewLocale || project.sourceLocale
  // Desktop writes PNGs straight into a folder; only the browser packages a ZIP.
  // Button copy follows the actual artifact.
  const isDesktop = isTauri()

  async function handleExport(layout: ExportLayout = 'default') {
    if (!project) return
    cancelledRef.current = false
    setStatus('running')
    setError(null)
    setDone(0)
    setFailures([])
    setCurrent(null)
    // Local mirror of `failures` — state updates are async, so we accumulate
    // here and decide all-ok / partial / total at the end from this array.
    const failed: RenderFailure[] = []

    const filePath = (loc: string, dev: string, n: string) =>
      layout === 'fastlane' ? `fastlane/screenshots/${loc}/${dev}_${n}.png` : `${loc}/${dev}/${n}.png`

    const useTauri = isTauri()
    const suffix = layout === 'fastlane' ? '-fastlane-screenshots' : '-screenshots'

    try {
      let outDir = ''
      const zip = useTauri ? null : new JSZip()
      if (useTauri) {
        const picked = await open({ directory: true, title: '스크린샷을 저장할 폴더 선택' })
        if (typeof picked !== 'string') {
          setStatus('idle')
          return
        }
        outDir = `${picked}/${sanitizePathSegment(project.name)}${suffix}`
      }
      // Sink: write straight to the chosen folder in the desktop app, or stage
      // into the in-memory zip in the browser. One file at a time either way.
      const emit = (path: string, data: Blob | string, opts?: JSZip.JSZipFileOptions) =>
        useTauri
          ? writeFileToDir(outDir, path, data, opts?.unixPermissions === '755')
          : Promise.resolve(void zip!.file(path, data, opts))

      let count = 0

      for (const locale of exportLocales) {
        let i = 0
        while (i < project.slides.length) {
          if (cancelledRef.current) {
            setStatus('idle')
            return
          }
          const slide = project.slides[i]
          const device = deviceOf(slide)
          const renderLocale = locale === project.sourceLocale ? null : locale
          const localeDir = ascExportCode(locale)
          setCurrent({ slideNo: slide.index + 1, locale })

          // Span leader → render the 2× canvas once, slice into both PNGs.
          // Skip the follower in the next iteration since it's already done.
          if (slide.spanGroupId && slide.spanRole === 'leader') {
            const follower = project.slides[i + 1]
            if (follower && follower.spanGroupId === slide.spanGroupId) {
              // Per-slide guard: a failure here records both halves and moves
              // on, so one broken span group can't abort the whole export.
              try {
                const { leader: leftBlob, follower: rightBlob } = await renderSpanGroup(
                  slide,
                  renderLocale,
                )
                const lName = String(slide.index + 1).padStart(2, '0')
                const rName = String(follower.index + 1).padStart(2, '0')
                await emit(filePath(localeDir, device, lName), leftBlob)
                await emit(filePath(localeDir, device, rName), rightBlob)
              } catch (e) {
                const message = e instanceof Error ? e.message : String(e)
                failed.push({ slideNo: slide.index + 1, locale, device, message })
                failed.push({ slideNo: follower.index + 1, locale, device, message })
                setFailures([...failed])
              }
              count += 2
              setDone(count)
              i += 2
              continue
            }
          }
          // Defensive: stray follower with no preceding leader. Skip — its
          // content was consumed by the leader pass or is genuinely orphaned.
          if (slide.spanRole === 'follower') {
            i++
            continue
          }

          // Per-slide guard: record the failure and continue so the rest of the
          // batch still renders and a partial ZIP/folder is produced.
          try {
            const blob = await renderSlide(slide, renderLocale)
            const name = String(slide.index + 1).padStart(2, '0')
            await emit(filePath(localeDir, device, name), blob)
          } catch (e) {
            const message = e instanceof Error ? e.message : String(e)
            failed.push({ slideNo: slide.index + 1, locale, device, message })
            setFailures([...failed])
          }
          count++
          setDone(count)
          i++
        }
      }

      setCurrent(null)

      // Total failure: every planned render failed, so there's nothing to
      // package. Skip the artifact and surface an error state (the per-slide
      // failure list stays visible alongside it).
      const rendered = count - failed.length
      if (rendered === 0 && failed.length > 0) {
        setError('모든 슬라이드 렌더링에 실패해 내보낼 파일이 없습니다.')
        setStatus('error')
        return
      }

      if (layout === 'fastlane') {
        await emit('fastlane/Appfile', FASTLANE_APPFILE)
        await emit('fastlane/Deliverfile', FASTLANE_DELIVERFILE)
        await emit('asc_api_key.json', FASTLANE_KEY_EXAMPLE)
        await emit('upload.sh', FASTLANE_UPLOAD_SH, { unixPermissions: '755' })
        await emit('README.txt', FASTLANE_README)
      }

      if (useTauri) {
        setStatus('done')
      } else {
        const zipBlob = await zip!.generateAsync({ type: 'blob' })
        saveAs(zipBlob, `${project.name}${suffix}.zip`)
        setStatus('done')
      }
    } catch (e) {
      setCurrent(null)
      setError(e instanceof Error ? e.message : String(e))
      setStatus('error')
    }
  }

  function handleCancel() {
    cancelledRef.current = true
  }

  const pct = total > 0 ? Math.round((done / total) * 100) : 0

  return (
    <div className="flex h-full flex-col overflow-hidden">
      <div className="flex flex-shrink-0 items-center justify-between border-b border-[var(--color-border)] px-6 py-3">
        <h2 className="text-lg font-semibold text-[var(--color-text)]">내보내기</h2>
        <button
          onClick={() => setStep(3)}
          className="rounded px-3 py-1.5 text-sm text-[var(--color-text-dim)] hover:text-[var(--color-text)]"
        >
          ← 로컬라이즈
        </button>
      </div>

      <div className="flex flex-1 flex-col gap-4 overflow-y-auto px-6 py-6">
        {untranslated.length > 0 && (
          <div className="rounded-lg border border-yellow-500/30 bg-yellow-500/10 p-3 text-xs text-yellow-700">
            번역 미완료 로케일 {untranslated.length}개: {untranslated.join(', ')} —
            소스 텍스트로 내보내집니다.
          </div>
        )}

        {missingScreenshots.length > 0 && (
          <div className="rounded-lg border border-yellow-500/30 bg-yellow-500/10 p-3 text-xs text-yellow-700">
            스크린샷 없는 슬라이드: {missingScreenshots.join(', ')} — 기기 프레임만
            내보내집니다.
          </div>
        )}

        {/* Preview section */}
        <div className="rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5">
          <div className="mb-3 flex items-center justify-between gap-3">
            <h3 className="flex items-center gap-2 text-sm font-semibold text-[var(--color-text)]">
              미리보기
              {previewLoading && (
                <span className="h-3.5 w-3.5 animate-spin rounded-full border-2 border-[var(--color-accent)] border-t-transparent" />
              )}
            </h3>
            <div className="flex items-center gap-3">
              <label className="flex items-center gap-1.5 text-xs text-[var(--color-text-dim)]" title="미리보기 크기">
                크기
                <input
                  type="range"
                  min={1}
                  max={5}
                  value={previewSize}
                  onChange={(e) => setPreviewSize(Number(e.target.value))}
                  className="w-20 accent-[var(--color-accent)]"
                />
              </label>
              <select
                value={effectiveLocale}
                onChange={(e) => setPreviewLocale(e.target.value)}
                className="rounded border border-[var(--color-border)] bg-[var(--color-bg)] px-2 py-1.5 text-xs text-[var(--color-text)]"
              >
                {allLocales.map((l) => (
                  <option key={l} value={l}>{localeLabel(l)}</option>
                ))}
              </select>
            </div>
          </div>
          <div className="grid gap-2" style={{ gridTemplateColumns: `repeat(${previewCols}, minmax(0, 1fr))` }}>
            {project.slides.map((s, i) => (
              <div
                key={s.id}
                className="overflow-hidden rounded-lg border border-[var(--color-border)] bg-[var(--color-bg)]"
              >
                {previewSrcs[i] ? (
                  <img src={previewSrcs[i]!} alt={`슬라이드 ${i + 1}`} className="w-full object-contain" />
                ) : (
                  <div className="flex aspect-[9/19] items-center justify-center text-xs text-[var(--color-text-dim)]">
                    {i + 1}…
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Export summary */}
        <div className="rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5">
          <h3 className="mb-3 text-sm font-semibold text-[var(--color-text)]">렌더링 범위</h3>
          <div className="space-y-1.5 text-sm text-[var(--color-text-dim)]">
            <div className="flex justify-between">
              <span>슬라이드</span>
              <span className="text-[var(--color-text)]">{project.slides.length}장</span>
            </div>
            <div className="flex justify-between">
              <span>디바이스</span>
              <span className="text-[var(--color-text)]">
                {devicesInUse.length > 0
                  ? devicesInUse.map((d) => (d === 'iphone' ? 'iPhone' : 'iPad')).join(', ')
                  : '—'}
              </span>
            </div>
            <div>
              <div className="mb-1.5 flex justify-between">
                <span>로케일</span>
                <div className="flex gap-2">
                  <button
                    onClick={() => setExcludedLocales(new Set())}
                    className="text-xs text-[var(--color-text-dim)] hover:text-[var(--color-accent)]"
                  >
                    모두 선택
                  </button>
                  <button
                    onClick={() => setExcludedLocales(new Set(allLocales))}
                    className="text-xs text-[var(--color-text-dim)] hover:text-[var(--color-accent)]"
                  >
                    전체 해제
                  </button>
                </div>
              </div>
              <div className="flex flex-wrap gap-1.5">
                {allLocales.map((l) => {
                  const on = !excludedLocales.has(l)
                  return (
                    <button
                      key={l}
                      onClick={() => {
                        const next = new Set(excludedLocales)
                        if (on) next.add(l)
                        else next.delete(l)
                        setExcludedLocales(next)
                      }}
                      className={`rounded border px-2 py-0.5 text-xs transition-colors ${
                        on
                          ? 'border-[var(--color-accent)] text-[var(--color-accent)]'
                          : 'border-[var(--color-border)] text-[var(--color-text-dim)] hover:border-[var(--color-text-dim)]'
                      }`}
                    >
                      {localeLabel(l)}
                    </button>
                  )
                })}
              </div>
            </div>
            <div className="flex justify-between border-t border-[var(--color-border)] pt-1.5">
              <span>총 PNG</span>
              <span className="font-semibold text-[var(--color-text)]">{total}개</span>
            </div>
          </div>
        </div>

        {(status === 'running' || status === 'done') && (
          <div className="space-y-2">
            <div className="flex justify-between text-xs text-[var(--color-text-dim)]">
              <span>
                {status === 'done'
                  ? '렌더링 완료'
                  : current
                  ? `슬라이드 ${current.slideNo} · ${localeLabel(current.locale)} (${done}/${total})`
                  : `${done} / ${total} 렌더링 중…`}
              </span>
              <span>{pct}%</span>
            </div>
            <div className="h-1.5 w-full overflow-hidden rounded-full bg-[var(--color-surface-2)]">
              <div
                className="h-full bg-[var(--color-accent)] transition-all duration-150"
                style={{ width: `${pct}%` }}
              />
            </div>
          </div>
        )}

        {failures.length > 0 && (
          <div className="space-y-1.5 rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-xs text-red-600">
            <p className="font-semibold">
              {status === 'error'
                ? `렌더링 실패: ${failures.length}개 슬라이드 — 내보낸 파일이 없습니다.`
                : `일부 슬라이드 렌더링 실패 (${failures.length}개). 나머지는 정상적으로 내보냈습니다.`}
            </p>
            <ul className="list-disc space-y-0.5 pl-4">
              {failures.map((f, idx) => (
                <li key={`${f.slideNo}-${f.locale}-${idx}`}>
                  슬라이드 {f.slideNo} ({localeLabel(f.locale)}) 렌더 실패: {f.message}
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Catastrophic errors only (e.g. ZIP packaging). A total render
            failure is already explained by the per-slide failures list above,
            so don't double-report it here. */}
        {error && failures.length === 0 && (
          <p className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-xs text-red-600">
            {error}
          </p>
        )}

        <div className="flex gap-2">
          <button
            onClick={() => handleExport('fastlane')}
            disabled={status === 'running' || exportLocales.length === 0}
            title="screenshots/<locale>/<device>_NN.png — fastlane deliver로 바로 업로드"
            className="rounded-lg border border-[var(--color-border)] px-4 py-3 text-sm font-semibold text-[var(--color-text)] hover:border-[var(--color-accent)] disabled:cursor-not-allowed disabled:opacity-50"
          >
            {isDesktop ? 'fastlane 폴더' : 'fastlane용 ZIP'}
          </button>
          <button
            onClick={() => handleExport('default')}
            disabled={status === 'running' || exportLocales.length === 0}
            className="flex-1 rounded-lg bg-[var(--color-accent)] px-4 py-3 text-sm font-semibold text-white hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-50"
          >
            {status === 'running'
              ? `렌더링 중… (${done}/${total})`
              : status === 'done'
              ? isDesktop ? '다시 내보내기' : 'ZIP 다시 다운로드'
              : exportLocales.length === 0
              ? '내보낼 언어를 선택하세요'
              : isDesktop
              ? `내보내기 · ${total}개 PNG`
              : `ZIP 내보내기 · ${total}개 PNG`}
          </button>
          {status === 'running' && (
            <button
              onClick={handleCancel}
              className="rounded-lg border border-[var(--color-border)] px-4 py-3 text-sm text-[var(--color-text-dim)] hover:text-[var(--color-text)]"
            >
              취소
            </button>
          )}
        </div>

        <details className="rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] p-3 text-xs text-[var(--color-text-dim)]">
          <summary className="cursor-pointer font-medium text-[var(--color-text)]">
            fastlane으로 App Store Connect에 업로드하는 법
          </summary>
          <ol className="mt-2 list-decimal space-y-1 pl-4">
            <li>「fastlane용 ZIP」을 받아 압축을 풉니다.</li>
            <li><code>fastlane/Appfile</code>에 앱 번들 ID를 입력합니다.</li>
            <li>
              App Store Connect → 사용자 및 액세스 → 통합 → App Store Connect API에서
              키(.p8)를 만들어 <code>asc_api_key.json</code>에 채웁니다.
            </li>
            <li>
              폴더에서 <code>./upload.sh</code> 실행
              (또는 <code>fastlane deliver --api_key_path ./asc_api_key.json</code>).
            </li>
          </ol>
          <p className="mt-2">
            스크린샷만 업로드되고(바이너리·메타데이터 제외), .p8 키는 내 컴퓨터에만 머뭅니다.
            fastlane 설치가 필요합니다.
          </p>
        </details>
      </div>
    </div>
  )
}
